target_machine:
  - x86_64
  - aarch64
  - powerpc64le
  - s390x
centos_machine:
  - x86_64
  - aarch64
  - ppc64le
  - s390x
cross_target_platform:
  - linux-64
  - linux-aarch64
  - linux-ppc64le
  - linux-s390x
sysroot_cdt_arch:
  - x86_64
  - aarch64
  - ppc64le
  - s390x

ctng_vendor:
  - conda
sysroot_cdt_name:
  - cos7

channel_targets:
  - conda-forge main
  - conda-forge sysroot-with-crypt

with_crypt:
  - false
  - true

zip_keys:
  - - target_machine
    - cross_target_platform
    - centos_machine
    - sysroot_cdt_arch
  - - channel_targets
    - with_crypt
